// Package crypto implements the Red Sky session key layer.
//
// Layered crypto:
//   1. TLS protects the wire.
//   2. On top of TLS, each session derives an AES-256-GCM key via X25519 ECDH
//      between an ephemeral key pair generated by the core (server side) and
//      an ephemeral key pair generated by the agent (client side).
//   3. Every payload after the handshake is AES-256-GCM encrypted with a
//      monotonic nonce. Replay is rejected by a sliding window.
//
// This means even if the TLS layer is compromised (bad proxy, MITM with a
// trusted cert, TLS downgrade), the attacker still can't read or forge tasks.
package crypto

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/ecdh"
	"crypto/rand"
	"crypto/sha256"
	"encoding/binary"
	"errors"
	"io"
	"sync"
)

const (
	KeySize   = 32 // AES-256
	NonceSize = 12 // GCM standard
	TagSize   = 16
)

var (
	ErrNonceReplay = errors.New("crypto: nonce replay")
	ErrShortFrame  = errors.New("crypto: short frame")
)

// Session holds the negotiated AES key and replay window state for one
// connection.
type Session struct {
	key     []byte
	aead    cipher.AEAD
	mu      sync.Mutex
	lastSeq uint64
	seen    map[uint64]bool
}

// GenerateEphemeralKey creates an X25519 key pair for ECDH.
func GenerateEphemeralKey() (*ecdh.PrivateKey, error) {
	curve := ecdh.X25519()
	return curve.GenerateKey(rand.Reader)
}

// DeriveKey computes the shared AES-256 key from an ephemeral private key and
// the peer's public key. Both sides compute the same value.
func DeriveKey(priv *ecdh.PrivateKey, peerPub []byte) ([]byte, error) {
	pub, err := ecdh.X25519().NewPublicKey(peerPub)
	if err != nil {
		return nil, err
	}
	shared, err := priv.ECDH(pub)
	if err != nil {
		return nil, err
	}
	// HKDF-lite: SHA-256 of the shared secret with a domain-separated prefix.
	h := sha256.New()
	h.Write([]byte("redsky-v3-session-key\x00"))
	h.Write(shared)
	return h.Sum(nil), nil
}

// NewSession creates a Session from a derived AES key.
func NewSession(key []byte) (*Session, error) {
	if len(key) != KeySize {
		return nil, errors.New("crypto: bad key size")
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}
	aead, err := cipher.NewGCM(block)
	if err != nil {
		return nil, err
	}
	return &Session{key: key, aead: aead, seen: make(map[uint64]bool)}, nil
}

// Encrypt wraps the payload with a fresh nonce and sequence number.
// Wire format: [8-byte seq BE][12-byte nonce][ciphertext+tag].
func (s *Session) Encrypt(plain []byte) ([]byte, error) {
	s.mu.Lock()
	s.lastSeq++
	seq := s.lastSeq
	s.mu.Unlock()

	nonce := make([]byte, NonceSize)
	if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
		return nil, err
	}
	out := make([]byte, 8+NonceSize)
	binary.BigEndian.PutUint64(out[0:8], seq)
	copy(out[8:8+NonceSize], nonce)

	ct := s.aead.Seal(nil, nonce, plain, out[0:8]) // seq as AAD
	return append(out, ct...), nil
}

// Decrypt verifies the sequence, rejects replays, and returns the plaintext.
func (s *Session) Decrypt(frame []byte) ([]byte, error) {
	if len(frame) < 8+NonceSize+TagSize {
		return nil, ErrShortFrame
	}
	seq := binary.BigEndian.Uint64(frame[0:8])
	nonce := frame[8:8+NonceSize]
	ct := frame[8+NonceSize:]

	s.mu.Lock()
	if s.seen[seq] {
		s.mu.Unlock()
		return nil, ErrNonceReplay
	}
	s.seen[seq] = true
	// Prune the window.
	if seq > 128 {
		delete(s.seen, seq-128)
	}
	s.mu.Unlock()

	return s.aead.Open(nil, nonce, ct, frame[0:8])
}

// Fingerprint returns the SHA-256 fingerprint of the AES key for logging.
func (s *Session) Fingerprint() string {
	h := sha256.Sum256(s.key)
	return fmtHex(h[:8])
}

func fmtHex(b []byte) string {
	const hex = "0123456789abcdef"
	out := make([]byte, len(b)*2)
	for i, v := range b {
		out[i*2] = hex[v>>4]
		out[i*2+1] = hex[v&0x0f]
	}
	return string(out)
}
