# language: Python, file: Program/evade/string_crypt.py, target: Red Sky evade — string crypt
# Compile-time string obfuscator. Takes a list of strings and produces a header
# with the ciphertexts, plus a matching C++ decryptor.

import sys
from pathlib import Path
from typing import List

from Program.theme.palette import SCARLET, ARTERY, BONE, ASH, OK, CLOT, RESET, BOLD
from Program.utils import load_config, print_ok, print_err, print_info, print_warn, print_kv, print_bullet
from Program.utils.paths import OUTPUT_DIR


FNV_OFFSET = 0x811C9DC5


def fnv1a(data: bytes, seed: int = FNV_OFFSET) -> int:
    h = seed
    for b in data:
        h ^= b
        h = (h * 0x01000193) & 0xFFFFFFFF
    return h


def xor_encrypt(plain: str, key: bytes) -> bytes:
    data = plain.encode()
    return bytes(data[i] ^ key[i % len(key)] for i in range(len(data)))


def gen_header(strings: List[str], key: bytes, header_name: str = "obf_strings") -> str:
    """Generate a C++ header with encrypted strings + a decryptor."""
    guard = header_name.upper() + "_H"
    lines = [f"// generated by redsky evade string_crypt — do not edit",
             f"#ifndef {guard}", f"#define {guard}", "",
             "#include <windows.h>", "#include <string>", "#include <vector>", "",
             f"static const BYTE {header_name}_key[{len(key)}] = {{",
             "    " + ", ".join(f"0x{b:02X}" for b in key),
             "};", ""]

    for i, s in enumerate(strings):
        enc = xor_encrypt(s, key)
        var = f"enc_str_{i}"
        lines.append(f"static const BYTE {var}[{len(enc) + 1}] = {{")
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in enc) + ", 0x00")
        lines.append("};")

    lines += ["",
              f"inline std::string {header_name}_decrypt(const BYTE* data, size_t len) {{",
              "    std::string out(len, 0);",
              f"    for (size_t i = 0; i < len; ++i)",
              f"        out[i] = data[i] ^ {header_name}_key[i % sizeof({header_name}_key)];",
              "    return out;",
              "}",
              "",
              "// usage:",
              f"//   auto s0 = {header_name}_decrypt(enc_str_0, sizeof(enc_str_0) - 1);",
              "",
              f"#endif // {guard}",
              ""]

    return "\n".join(lines)


def cmd_gen(args: List[str]) -> int:
    if not args:
        print_err("usage: redsky evade string_crypt <string> [string2] ... [--key hex] [--out file]")
        return 2

    key = b"redsky_default_key_16b!"  # 22 bytes
    strings = []
    out_file = ""

    i = 0
    while i < len(args):
        a = args[i]
        if a == "--key" and i + 1 < len(args):
            try:
                key = bytes.fromhex(args[i + 1])
                i += 2
                continue
            except ValueError:
                print_err("key must be hex")
                return 2
        if a == "--out" and i + 1 < len(args):
            out_file = args[i + 1]
            i += 2
            continue
        strings.append(a)
        i += 1

    if not strings:
        print_err("no strings to encrypt")
        return 2

    print_info(f"encrypting {len(strings)} string(s)")
    print_kv("key", key.hex())
    print()

    header = gen_header(strings, key)
    print(header[:1500])

    out = Path(out_file) if out_file else OUTPUT_DIR / "evade" / "obf_strings.hpp"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(header)
    print()
    print_kv("saved", out)
    return 0


def run_cli(args: List[str]) -> int:
    return cmd_gen(args)


if __name__ == "__main__":
    sys.exit(run_cli(sys.argv[1:]))
